### ISSUE TITLE
uncaught TypeError: $(...).AniView is not a function

### ISSUE THREAD

**Issue by colcrt** [jjcosgrove/jquery-aniview#20]
i don't know if that's why i use jquery version 3.4.1 any idea?

**Comment by jjcosgrove** [comment]
@colcrt not sure what your issue is... but it should work fine with jQuery 3.4.1...

This fiddle appears to be using the latest version and is still working 🤔 

https://jsfiddle.net/dvgbu3sc/1/

**Comment by jjcosgrove** [comment]
Closing due to lack of activity/response... assumed to be working, OK.

Thanks.
